### ISSUE TITLE
content of titleStmt, editionStmt, publicationStmt

### ISSUE THREAD

**Issue by holfordm** [holfordm/tolkien-xml#10]
James, could you let me know what if anything you want to change about these so I can double check? You mentioned moving the content of `<title type="collection">` to `<collection>` in `<msIdentifier`> for example.

**Comment by jamescummings** [comment]
That was a possibility that so far I've not done.  (I still could if you think it a good idea.)  What might be better is to put in in collection *if* it exists and collection doesn't.

In publicationStmt there are some which look like:

````
 <publicationStmt>
            <pubPlace>Oxford</pubPlace>
            <publisher>Bodleian Library</publisher>
 </publicationStmt>
````
However there is a TEI rule that has existed in prose for ages but only recently (since 2014) is actually being enforced that says one of publisher, distributor, or authority need to be given first.  I spent quite awhile trying to figure out tests for the pubPlace coming first and reversing them and such ... all which are much harder to do than I thought...but my cunning solution is this:

Where publicationStmt does not have a p element add an authority element with the content 'Bodleian Libraries' immediately inside publicationStmt before anything else.  authority is unused in the oxford records, and it isn't untrue, so seems like a way to solve this without reversing it.

**Comment by holfordm** [comment]
alternatively could this be a find-and-replace job?



________________________________

**Comment by jamescummings** [comment]
Probably not, there might be so many variants. I.e. there are places where there is pubPlace, then something like idno, then publisher.  i.e. they don't exactly match this.

**Comment by holfordm** [comment]
I think that the problem may be confined to the "Barocci_summary" folder and could be fixed by find and replace, but let me know if you have better information

**Comment by jamescummings** [comment]
This is resolved in the new data and consistent across all collections. closing.
